env               = "dev"
aws_region        = "us-east-1"
vpc_cidr          = "10.0.0.0/16"
instance_type     = "t3.micro"
worker_count      = 2
github_org        = "https://github.com/mohan6451"       # replace
github_repo       = "terraform-devops-portfolio"
allowed_ssh_cidrs = ["122.x.x.x/32"]      # replace with your IP
public_key_path   = "~/.ssh/k3s-key.pub"
